# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchases',
        ),
    ]
