# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Receipt',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='purchases',
            new_name='receipts',
        ),
    ]
